import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.*;
import java.sql.*;
import java.io.File;

public class DbLibraryStoreTest {
    private DbLibraryStore store;

    private static final String DB_URL = "jdbc:h2:./test;AUTO_SERVER=TRUE";
    private static final String USER = "sa";
    private static final String PASS = "";

    private Connection connect() throws SQLException {
        return DriverManager.getConnection(DB_URL, USER, PASS);
    }

    @BeforeEach
    void setUp() {
        store = new DbLibraryStore();
        try (Connection conn = this.connect(); Statement stmt = conn.createStatement()) {
            // Disable checks to allow complete deletion
            stmt.execute("SET REFERENTIAL_INTEGRITY FALSE");

            // Truncate and reset auto-increment IDs
            stmt.execute("TRUNCATE TABLE LOANS RESTART IDENTITY");
            stmt.execute("TRUNCATE TABLE LIBRARYITEMS RESTART IDENTITY");
            stmt.execute("TRUNCATE TABLE MEMBERS");
            stmt.execute("TRUNCATE TABLE BOOKS");

            // Re-enable checks
            stmt.execute("SET REFERENTIAL_INTEGRITY TRUE");
        } catch (SQLException e) {
            e.printStackTrace();
        }
        store.initializeData(); // Ensure tables and sample books exist
    }

    @Test
    void testLogFileExists(){
        File logFile = new File("logs/db_activity.log");
        assertTrue(logFile.exists(), "The log file 'logs/db_activity.log' should be created by Log4j2");
    }

    @Test
    void testLoggingForAccountDeletion(){
        Member testMember = new Member(0, "Jane", "Doe", 1, 8888L, 0, 0, false, null);
        store.addMember(testMember);
        String memberId = String.valueOf(testMember.getId());

        //trigger multiple suspensions for deletion
        store.suspendMember(memberId);
        store.suspendMember(memberId);
        store.suspendMember(memberId);

        Member deletedMember = store.getMember(memberId);
        assertNull(deletedMember, "Member should be deleted after 3 suspensions.");
        // Manual Check: Look for "FATAL" in db_activity.log or console
    }

    @Test
    void testLoggingBorrowLimitExceeded() {
        Member undergrad = new Member(0, "Student", "One", 1, 1234L, 0, 0, false, null);
        store.addMember(undergrad);
        String memberId = String.format("%04d", undergrad.getId());

        int isbn = 102938; // 1984
        store.lendItem(memberId, isbn);
        store.lendItem(memberId, isbn);
        store.lendItem(memberId, isbn);

        assertFalse(store.canMemberBorrow(memberId), "Undergraduate cannot borrow more than 3 items.");
        // Manual Check: Look for logger statements regarding borrowing checks in console
    }

    @Test
    void testAddAndGetBook() {
        // Arrange
        Book testBook = new Book("Test Driven Development", 987654, "Kent Beck", 2002);

        // Act
        store.addBook(testBook);
        Book retrieved = store.getBook("987654");

        // Assert
        assertNotNull(retrieved);
        assertEquals("Test Driven Development", retrieved.getTitle());
        assertEquals("Kent Beck", retrieved.getAuthor());
        assertEquals(987654, retrieved.getISBN());
    }

    @Test
    void testAddAndGetAndDeleteMember() { //Test adding and retrieving a member
        // Create a template member; the ID field here will be overwritten by the store
        Member testMember = new Member(0, "John", "Doe", 1, 9999L, 0, 0, false, null);

        store.addMember(testMember);

        // Capture the ID generated by the store
        String memberId = String.format("%04d", testMember.getId());

        Member retrieved = store.getMember(memberId);

        assertNotNull(retrieved);
        assertEquals("John", retrieved.getFirstName());
        assertEquals("Doe", retrieved.getLastName());
        assertEquals(9999L, retrieved.getSsn());

        store.removeMember(memberId);
        Member deletedMember = store.getMember(memberId);
        assertNull(deletedMember);
    }

    @Test
    void testSuspendMember() { // Test member suspension logic
        Member testMember = new Member(0, "Jane", "Doe", 1, 8888L, 0, 0, false, null);
        store.addMember(testMember);

        // Use the generated ID
        String memberId = String.valueOf(testMember.getId());

        store.suspendMember(memberId);
        assertTrue(store.isSuspendedMember(memberId));

        store.suspendMember(memberId);
        store.suspendMember(memberId);

        Member deletedMember = store.getMember(memberId);
        assertNull(deletedMember);
    }

    @Test
    void testLendAndReturnItem() {
        int isbn = 999999;
        store.addBook(new Book("Test Book", isbn, "Author", 2024));
        store.addLibraryItem(isbn);

        Member testMember = new Member(0, "Alice", "Smith", 1, 7777L, 0, 0, false, null);
        store.addMember(testMember);
        String memberId = String.valueOf(testMember.getId());

        Long loanId = store.lendItem(memberId, isbn);

        assertNotEquals(-1L, loanId);

        boolean returnSuccess = store.returnItem(memberId, isbn);
        assertTrue(returnSuccess);
    }

    @Test
    void testCanMemberBorrowLimits() {
        int isbn = 238103;
        store.addLibraryItem(isbn);
        store.addLibraryItem(isbn);
        store.addLibraryItem(146123);

        Member testMember = new Member(0, "Bob", "Builder", 1, 6666L, 0, 0, false, null);
        store.addMember(testMember);
        String memberId = String.valueOf(testMember.getId());

        assertTrue(store.canMemberBorrow(memberId));

        store.lendItem(memberId, isbn);
        store.lendItem(memberId, isbn);
        store.lendItem(memberId, 146123);

        assertFalse(store.canMemberBorrow(memberId));
    }

    @Test
    void testGetLoan() {
        int isbn = 174213;
        store.addLibraryItem(isbn);

        Member testMember = new Member(0, "Charlie", "Brown", 2, 4444L, 0, 0, false, null);
        store.addMember(testMember);
        String memberId = String.valueOf(testMember.getId());

        long generatedId = store.lendItem(memberId, isbn);

        assertNotEquals(-1, generatedId);

        Loan activeLoan = store.getLoan(generatedId);
        assertNotNull(activeLoan);
        // Convert int ID to String for comparison if necessary,
        // or compare as integers depending on the Loan object implementation
        assertEquals(testMember.getId(), activeLoan.getMemberId());
        assertNotNull(activeLoan.getDueDate());
    }
}
